#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <d3d11.h>
#include <tlhelp32.h>
#include <psapi.h>
#include <shlobj.h>
#include <commdlg.h>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <random>
#include <thread>
#include <mutex>
#include <vector>
#include <string>
#include <algorithm>
#include <chrono>
#include <cstring>
#include "imgui.h"
#include "backends/imgui_impl_win32.h"
#include "backends/imgui_impl_dx11.h"
extern "C" {
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
}

static ID3D11Device* gDevice=nullptr; static ID3D11DeviceContext* gContext=nullptr; static IDXGISwapChain* gSwapChain=nullptr; static ID3D11RenderTargetView* gRTV=nullptr;
static HWND gWnd=nullptr; static HANDLE gProcess=nullptr; static DWORD gPid=0; static std::mutex gMutex;
static std::string gStatus="Ready"; static std::vector<std::string> gLogs; static std::string gCode="-- Neon Debugger\nprint('Lua 5.4 ready')\n"; static bool gAutoAttach=false;
static constexpr wchar_t kTarget[]=L"NeonDebugTarget.exe";

static void Log(const std::string& s,const char* level="INFO") { std::lock_guard<std::mutex> l(gMutex); auto now=std::chrono::system_clock::to_time_t(std::chrono::system_clock::now()); tm tmv{}; localtime_s(&tmv,&now); char t[32]; strftime(t,sizeof(t),"%H:%M:%S",&tmv); gLogs.push_back(std::string("[")+t+"]["+level+"] "+s); if(gLogs.size()>400) gLogs.erase(gLogs.begin(),gLogs.begin()+50); }
static std::wstring Wide(const std::string& s){int n=MultiByteToWideChar(CP_UTF8,0,s.c_str(),-1,nullptr,0); std::wstring w(n,0); MultiByteToWideChar(CP_UTF8,0,s.c_str(),-1,w.data(),n); if(!w.empty()&&w.back()==0)w.pop_back(); return w;}
static std::string Narrow(const std::wstring& w){int n=WideCharToMultiByte(CP_UTF8,0,w.c_str(),-1,nullptr,0,nullptr,nullptr); std::string s(n,0); WideCharToMultiByte(CP_UTF8,0,w.c_str(),-1,s.data(),n,nullptr,nullptr); if(!s.empty()&&s.back()==0)s.pop_back(); return s;}
static DWORD FindTarget(){HANDLE h=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0); if(h==INVALID_HANDLE_VALUE)return 0; PROCESSENTRY32W e{sizeof(e)}; DWORD p=0; if(Process32FirstW(h,&e)){do{if(!_wcsicmp(e.szExeFile,kTarget)){p=e.th32ProcessID;break;}}while(Process32NextW(h,&e));} CloseHandle(h); return p;}
static void Detach(){std::lock_guard<std::mutex> l(gMutex); if(gProcess){CloseHandle(gProcess);gProcess=nullptr;}gPid=0;gStatus="Ready";}
static bool Attach(DWORD pid){if(!pid)return false; HANDLE h=OpenProcess(PROCESS_QUERY_INFORMATION|PROCESS_VM_READ|PROCESS_VM_WRITE|PROCESS_VM_OPERATION,FALSE,pid); if(!h){Log("OpenProcess failed: "+std::to_string(GetLastError()),"ERROR");return false;} Detach(); {std::lock_guard<std::mutex> l(gMutex);gProcess=h;gPid=pid;gStatus="Attached";} Log("Attached to NeonDebugTarget.exe"); return true;}
static void KillTarget(){DWORD pid=FindTarget(); if(!pid){Log("No NeonDebugTarget.exe process found","WARN");return;} HANDLE h=OpenProcess(PROCESS_TERMINATE|PROCESS_QUERY_LIMITED_INFORMATION,FALSE,pid); if(!h){Log("Terminate access denied/error: "+std::to_string(GetLastError()),"ERROR");return;} if(TerminateProcess(h,0)){Log("Debug target terminated","WARN");gStatus="Killed";Detach();}else Log("TerminateProcess failed: "+std::to_string(GetLastError()),"ERROR"); CloseHandle(h);}

static uintptr_t ParseAddr(lua_State* L,int i){if(lua_isinteger(L,i))return (uintptr_t)lua_tointeger(L,i); size_t n=0; const char* s=luaL_checklstring(L,i,&n); return (uintptr_t)strtoull(s,nullptr,0);}
static int l_log(lua_State*L){Log(luaL_tolstring(L,1,nullptr));lua_pop(L,1);return 0;}
static int l_read(lua_State*L){if(!gProcess)return luaL_error(L,"not attached"); uintptr_t a=ParseAddr(L,1); size_t n=(size_t)luaL_checkinteger(L,2); if(n>1024*1024)return luaL_error(L,"size too large"); std::string b(n,'\\0'); SIZE_T got=0; if(!ReadProcessMemory(gProcess,(void*)a,b.data(),n,&got))return luaL_error(L,"ReadProcessMemory failed"); lua_pushlstring(L,b.data(),got);return 1;}
static int l_write(lua_State*L){if(!gProcess)return luaL_error(L,"not attached"); uintptr_t a=ParseAddr(L,1); size_t n=0; const char* b=luaL_checklstring(L,2,&n); SIZE_T wrote=0; if(!WriteProcessMemory(gProcess,(void*)a,b,n,&wrote))return luaL_error(L,"WriteProcessMemory failed"); lua_pushinteger(L,(lua_Integer)wrote);return 1;}
static int l_procs(lua_State*L){lua_newtable(L);HANDLE h=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);PROCESSENTRY32W e{sizeof(e)};int i=1;if(h!=INVALID_HANDLE_VALUE&&Process32FirstW(h,&e)){do{if(!_wcsicmp(e.szExeFile,kTarget)){lua_newtable(L);lua_pushinteger(L,e.th32ProcessID);lua_setfield(L,-2,"pid");lua_pushstring(L,Narrow(e.szExeFile).c_str());lua_setfield(L,-2,"name");lua_rawseti(L,-2,i++);}}while(Process32NextW(h,&e));}if(h!=INVALID_HANDLE_VALUE)CloseHandle(h);return 1;}
static int l_module(lua_State*L){if(!gProcess)return luaL_error(L,"not attached");const char* want=luaL_checkstring(L,1);HMODULE mods[1024];DWORD cb=0;if(!EnumProcessModules(gProcess,mods,sizeof(mods),&cb))return luaL_error(L,"EnumProcessModules failed");for(unsigned i=0;i<cb/sizeof(HMODULE);++i){char name[MAX_PATH]{};GetModuleBaseNameA(gProcess,mods[i],name,sizeof(name));if(!_stricmp(name,want)){MODULEINFO mi{};GetModuleInformation(gProcess,mods[i],&mi,sizeof(mi));lua_pushinteger(L,(lua_Integer)(uintptr_t)mi.lpBaseOfDll);return 1;}}lua_pushnil(L);return 1;}
static int l_wallpaper(lua_State*L){const char* p=luaL_checkstring(L,1);std::wstring w=Wide(p);if(!SystemParametersInfoW(SPI_SETDESKWALLPAPER,0,(PVOID)w.c_str(),SPIF_UPDATEINIFILE|SPIF_SENDCHANGE))return luaL_error(L,"SPI_SETDESKWALLPAPER failed");Log("Wallpaper changed");return 0;}
static void OpenLua(){lua_State* L=luaL_newstate();luaL_openlibs(L);lua_register(L,"print",l_log);lua_register(L,"warn",l_log);lua_register(L,"readMemory",l_read);lua_register(L,"writeMemory",l_write);lua_register(L,"getProcessList",l_procs);lua_register(L,"getModuleBase",l_module);lua_register(L,"setWallpaper",l_wallpaper);int r=luaL_dostring(L,gCode.c_str());if(r!=LUA_OK){const char* e=lua_tostring(L,-1);Log(e?e:"Lua error","ERROR");}else Log("Lua script completed","OK");lua_close(L);}
static bool SaveText(){OPENFILENAMEW ofn{sizeof(ofn)};wchar_t path[MAX_PATH]=L"script.lua";ofn.hwndOwner=gWnd;ofn.lpstrFile=path;ofn.nMaxFile=MAX_PATH;ofn.lpstrFilter=L"Lua (*.lua)\\0*.lua\\0Text (*.txt)\\0*.txt\\0\\0";ofn.Flags=OFN_OVERWRITEPROMPT;ofn.lpstrDefExt=L"lua";if(!GetSaveFileNameW(&ofn))return false;std::ofstream f(ofn.lpstrFile);f<<gCode;Log("Script saved: "+Narrow(path));return true;}
static bool LoadText(){OPENFILENAMEW ofn{sizeof(ofn)};wchar_t path[MAX_PATH]{};ofn.hwndOwner=gWnd;ofn.lpstrFile=path;ofn.nMaxFile=MAX_PATH;ofn.lpstrFilter=L"Lua (*.lua)\\0*.lua\\0Text (*.txt)\\0*.txt\\0\\0";ofn.Flags=OFN_FILEMUSTEXIST; if(!GetOpenFileNameW(&ofn))return false;std::ifstream f(ofn.lpstrFile);std::stringstream ss;ss<<f.rdbuf();gCode=ss.str();Log("Script loaded: "+Narrow(path));return true;}
static void RandomWallpaper(){PWSTR folder=nullptr;if(SHGetKnownFolderPath(FOLDERID_Pictures,0,nullptr,&folder)!=S_OK)return;std::vector<std::filesystem::path> imgs;try{for(auto& e:std::filesystem::directory_iterator(folder)){auto ext=e.path().extension().wstring();std::transform(ext.begin(),ext.end(),ext.begin(),towlower);if(ext==L".jpg"||ext==L".jpeg"||ext==L".png"||ext==L".bmp")imgs.push_back(e.path());}}catch(...){}CoTaskMemFree(folder);if(imgs.empty()){Log("No images found in Pictures","WARN");return;}std::mt19937 rng((unsigned)GetTickCount());auto p=imgs[rng()%imgs.size()];if(SystemParametersInfoW(SPI_SETDESKWALLPAPER,0,(PVOID)p.c_str(),SPIF_UPDATEINIFILE|SPIF_SENDCHANGE))Log("Wallpaper changed: "+Narrow(p.wstring()),"OK");else Log("Wallpaper change failed","ERROR");}
static void Watcher(){DWORD last=0;while(gAutoAttach){DWORD p=FindTarget();if(p&&p!=last){Attach(p);last=p;}if(!p)last=0;Sleep(2000);}}
static std::string LineNumbers(){int n=1;std::string s;for(char c:gCode)if(c=='\\n')++n;for(int i=1;i<=n;++i){s+=std::to_string(i);s+='\\n';}return s;}

static void Theme(){ImGuiStyle& s=ImGui::GetStyle();s.WindowRounding=7;s.ChildRounding=5;s.FrameRounding=4;s.ScrollbarRounding=5;s.WindowPadding={10,10};s.ItemSpacing={7,6};auto& c=s.Colors;c[ImGuiCol_WindowBg]=ImVec4(.025f,.035f,.05f,.97f);c[ImGuiCol_ChildBg]=ImVec4(.02f,.028f,.04f,.92f);c[ImGuiCol_FrameBg]=ImVec4(.04f,.055f,.075f,1);c[ImGuiCol_FrameBgHovered]=ImVec4(0,.35f,.3f,.25f);c[ImGuiCol_Button]=ImVec4(.03f,.08f,.09f,1);c[ImGuiCol_ButtonHovered]=ImVec4(0,.55f,.45f,.35f);c[ImGuiCol_ButtonActive]=ImVec4(0,.9f,.75f,.45f);c[ImGuiCol_Header]=ImVec4(0,.45f,.38f,.25f);c[ImGuiCol_HeaderHovered]=ImVec4(0,.8f,.65f,.35f);c[ImGuiCol_Text]=ImVec4(.82f,.9f,.92f,1);c[ImGuiCol_Border]=ImVec4(0,.9f,.7f,.18f);}
static void Draw(){ImGui::SetNextWindowPos({0,0});ImGui::SetNextWindowSize(ImGui::GetIO().DisplaySize);ImGui::Begin("##root",nullptr,ImGuiWindowFlags_NoDecoration|ImGuiWindowFlags_NoMove|ImGuiWindowFlags_NoSavedSettings);
ImGui::BeginChild("top",{0,48},true);ImGui::TextColored({0,.9f,.75f,1},"NEON DEBUGGER");ImGui::SameLine();ImGui::TextDisabled("  /  C++ / IMGUI / LUA");ImGui::SameLine(ImGui::GetWindowWidth()-330);ImGui::Text("Target:");ImGui::SameLine();ImGui::Button("NeonDebugTarget.exe",{170,0});ImGui::SameLine();ImGui::TextColored(gStatus=="Attached"?ImVec4(0.1f,1,.45f,1):ImVec4(1,.2f,.4f,1),"● %s",gStatus.c_str());ImGui::EndChild();
ImGui::BeginChild("side",{170,0},true);ImGui::TextColored({1,.0f,.4f,1},"CONTROL");ImGui::Separator();if(ImGui::Button("INJECT",{-1,34}))Log("Injection into external processes is disabled; use the local debug target API","WARN");if(ImGui::Button("KILL",{-1,34}))KillTarget();if(ImGui::Button("ATTACH",{-1,34})){DWORD p=FindTarget();if(p)Attach(p);else Log("Start NeonDebugTarget.exe first","WARN");}if(ImGui::Button("DETACH",{-1,34}))Detach();ImGui::Separator();if(ImGui::Button("EXECUTE  [F5]",{-1,34}))OpenLua();if(ImGui::Button("SAVE",{-1,30}))SaveText();if(ImGui::Button("LOAD",{-1,30}))LoadText();if(ImGui::Button("WALLPAPER",{-1,30}))RandomWallpaper();ImGui::Checkbox("Auto-attach",&gAutoAttach);static bool old=false;if(gAutoAttach&&!old)std::thread(Watcher).detach();old=gAutoAttach;ImGui::Spacing();ImGui::TextDisabled("Safe target only");ImGui::TextWrapped("This build does not inject into Roblox or other third-party clients.");ImGui::EndChild();ImGui::SameLine();
ImGui::BeginGroup();float w=ImGui::GetContentRegionAvail().x;float h=ImGui::GetContentRegionAvail().y;ImGui::BeginChild("editor",{w,h*.64f},true);ImGui::TextColored({0,.95f,.78f,1},"LUA SCRIPT EDITOR");ImGui::SameLine();ImGui::TextDisabled("Lua 5.4");ImGui::Separator();ImGui::BeginChild("numbers",{38,ImGui::GetContentRegionAvail().y},true,ImGuiWindowFlags_NoScrollbar);ImGui::TextUnformatted(LineNumbers().c_str());ImGui::EndChild();ImGui::SameLine();ImGui::InputTextMultiline("##code",gCode.data(),gCode.capacity()+1,{ImGui::GetContentRegionAvail().x,ImGui::GetContentRegionAvail().y},ImGuiInputTextFlags_AllowTabInput);ImGui::EndChild();
ImGui::BeginChild("console",{w,0},true);ImGui::TextColored({1,.0f,.4f,1},"CONSOLE");ImGui::SameLine(ImGui::GetWindowWidth()-80);if(ImGui::SmallButton("CLEAR"))gLogs.clear();ImGui::Separator();ImGui::BeginChild("logs",{0,0},false);for(auto& l:gLogs){ImVec4 col={.7f,.78f,.82f,1};if(l.find("[ERROR]")!=std::string::npos)col={1,.25f,.35f,1};else if(l.find("[WARN]")!=std::string::npos)col={1,.65f,.2f,1};else if(l.find("[OK]")!=std::string::npos)col={0,.95f,.65f,1};ImGui::TextColored(col,"%s",l.c_str());}if(ImGui::GetScrollY()>=ImGui::GetScrollMaxY()-5)ImGui::SetScrollHereY(1);ImGui::EndChild();ImGui::EndChild();ImGui::EndGroup();ImGui::End();}

static LRESULT WINAPI WndProc(HWND h,UINT m,WPARAM w,LPARAM l){if(ImGui_ImplWin32_WndProcHandler(h,m,w,l))return 1;if(m==WM_SIZE&&gDevice&&w!=SIZE_MINIMIZED){if(gRTV){gRTV->Release();gRTV=nullptr;}gSwapChain->ResizeBuffers(0,LOWORD(l),HIWORD(l),DXGI_FORMAT_UNKNOWN,0);ID3D11Texture2D* b=nullptr;gSwapChain->GetBuffer(0,IID_PPV_ARGS(&b));gDevice->CreateRenderTargetView(b,nullptr,&gRTV);b->Release();}if(m==WM_DESTROY){PostQuitMessage(0);return 0;}return DefWindowProc(h,m,w,l);}
static bool InitD3D(){DXGI_SWAP_CHAIN_DESC sd{};sd.BufferCount=2;sd.BufferDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;sd.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;sd.OutputWindow=gWnd;sd.SampleDesc.Count=1;sd.Windowed=TRUE;sd.SwapEffect=DXGI_SWAP_EFFECT_DISCARD;D3D_FEATURE_LEVEL fl;const D3D_FEATURE_LEVEL fs[]={D3D_FEATURE_LEVEL_11_0};if(FAILED(D3D11CreateDeviceAndSwapChain(nullptr,D3D_DRIVER_TYPE_HARDWARE,nullptr,0,fs,1,D3D11_SDK_VERSION,&sd,&gSwapChain,&gDevice,&fl,&gContext)))return false;ID3D11Texture2D* b=nullptr;gSwapChain->GetBuffer(0,IID_PPV_ARGS(&b));gDevice->CreateRenderTargetView(b,nullptr,&gRTV);b->Release();return true;}
int WINAPI WinMain(HINSTANCE hi,HINSTANCE,LPSTR,int){WNDCLASSEXW wc{sizeof(wc),CS_CLASSDC,WndProc,0,0,hi,nullptr,nullptr,nullptr,nullptr,L"NeonDebugger",nullptr};RegisterClassExW(&wc);gWnd=CreateWindowW(wc.lpszClassName,L"Neon Debugger",WS_OVERLAPPEDWINDOW,100,100,1180,760,nullptr,nullptr,hi,nullptr);if(!gWnd||!InitD3D())return 1;ShowWindow(gWnd,SW_SHOWDEFAULT);UpdateWindow(gWnd);IMGUI_CHECKVERSION();ImGui::CreateContext();Theme();ImGui_ImplWin32_Init(gWnd);ImGui_ImplDX11_Init(gDevice,gContext);Log("Neon Debugger initialized");MSG msg{};while(msg.message!=WM_QUIT){while(PeekMessage(&msg,nullptr,0,0,PM_REMOVE)){TranslateMessage(&msg);DispatchMessage(&msg);}ImGui_ImplDX11_NewFrame();ImGui_ImplWin32_NewFrame();ImGui::NewFrame();Draw();ImGui::Render();const float clear[]={.008f,.012f,.018f,1};gContext->OMSetRenderTargets(1,&gRTV,nullptr);gContext->ClearRenderTargetView(gRTV,clear);ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());gSwapChain->Present(1,0);}gAutoAttach=false;Detach();ImGui_ImplDX11_Shutdown();ImGui_ImplWin32_Shutdown();ImGui::DestroyContext();if(gRTV)gRTV->Release();if(gSwapChain)gSwapChain->Release();if(gContext)gContext->Release();if(gDevice)gDevice->Release();DestroyWindow(gWnd);UnregisterClassW(wc.lpszClassName,hi);return 0;}
